kind: azureCloud
environmentName: ${TYGER_ENVIRONMENT_NAME}

cloud:
  tenantId: 72f988bf-86f1-41af-91ab-2d7cd011db47
  subscriptionId: 87d8acb3-5176-4651-b457-6ab9cefd8e3d
  resourceGroup: ${TYGER_ENVIRONMENT_NAME}
  defaultLocation: ${TYGER_LOCATION}

  # Tags to apply to all resources and resource groups
  resourceTags:
    tyger-development: "true"

  # Whether to use private networking. The default is false.
  # If true, Tyger service, storage storage accounts, and all other created resources
  # will not be accessible from the public internet.
  privateNetworking: true

  # Optionally point an existing Log Analytics workspace to send logs to.
  logAnalyticsWorkspace:
    resourceGroup: eminence
    name: eminence

  # Optionaly use a custom DNS zone
  dnsZone:
    resourceGroup: eminence
    name: eminence.ms

  # Optionally provide a TLS certificate, if not using Let's Encrypt
  tlsCertificate:
    keyVault:
      resourceGroup: eminence
      name: eminence
    certificateName: eminence-tls-cert

  compute:
    clusters:
      - name: ${TYGER_ENVIRONMENT_NAME}
        apiHost: true
        kubernetesVersion: "1.33"
        sku: Standard
        # location: defaults to Standard

        # An existing virtual network subnet to deploy the cluster into.
        existingSubnet:
          resourceGroup: eminence
          vnetName: eminence-pl-${TYGER_LOCATION}-vnet
          subnetName: default

        # A CIDR notation IP range from which to assign pod IPs.
        # This range must not overlap with the service CIDR range, the cluster subnet range,
        # and IP ranges used in peered VNets and on-premises networks.
        # podCidr: defaults to 10.244.0.0/16

        # A CIDR notation IP range from which to assign service cluster IPs.
        # This range must not overlap with the pod CIDR range, the cluster subnet range,
        # and IP ranges used in peered VNets and on-premises networks.
        serviceCidr: 10.2.0.0/16

        # The IP address assigned to the Kubernetes DNS service.
        # It must be within the service address range specified in serviceCidr.
        dnsServiceIp: 10.2.0.10

        systemNodePool:
          name: system
          vmSize: ${TYGER_SYSTEM_NODE_SKU}
          minCount: 1
          maxCount: 3
          # osSku: defaults to AzureLinux

        userNodePools:
          - name: cpunp
            vmSize: ${TYGER_CPU_NODE_SKU}
            minCount: ${TYGER_MIN_CPU_NODE_COUNT}
            maxCount: 10
            # osSku: defaults to AzureLinux

        outboundIpServiceTags:
          - type: FirstPartyUsage
            tag: /NonProd

    # These are the principals that will have the ability to run `tyger api install`.
    # They will have access to the "tyger" namespace in each cluster and will have
    # the necessary Azure RBAC role assignments.
    # For users:
    #   "kind" must be set to "User"
    #   "objectId" must be set to the object ID GUID
    #   "userPrincipalName" must be set (this is usually the email address, unless this is a guest account)
    # For groups:
    #   "kind" must be set to "Group"
    #   "objectId" must be set to the object ID GUID
    # For service principals:
    #   "kind" must be set to "ServicePrincipal"
    #   "objectId" must be set to the object ID GUID
    managementPrincipals:
      - kind: ServicePrincipal
        objectId: 2e092785-472a-4ea1-9700-4d15646d9e91
      - kind: Group
        objectId: 36043a62-1383-4012-95aa-44da0a4d8012

    localDevelopmentIdentityId: 36043a62-1383-4012-95aa-44da0a4d8012

    # The names of private container registries that the clusters must
    # be able to pull from.
    privateContainerRegistries:
      - eminence

    # This must be set if using a custom DNS zone and needs to be globally unique for the Azure region.
    # Each organization's domain name will have a CNAME record pointing to the domain name formed
    # by this value, which will be <dnslabel>.<region>.cloudapp.azure.com
    dnsLabel: ${TYGER_ENVIRONMENT_NAME}-tyger

    # Optional Helm chart overrides
    # helm:
    #   traefik:
    #     repoName:
    #     repoUrl: not set if using `chartRef`
    #     chartRef: e.g. oci://...
    #     version:
    #     values:
    #   certManager:
    #   nvidiaDevicePlugin:

  database:
    serverName: ${TYGER_ENVIRONMENT_NAME}-tyger
    postgresMajorVersion: 16
    location: ${TYGER_DATABASE_LOCATION}
    computeTier: GeneralPurpose
    vmSize: Standard_D2s_v3
    # storageSizeGB: Defaults to 32 (the minimum supported)
    # backupRetentionDays: Defaults to 7
    # backupGeoRedundancy: Defaults to false

    # Firewall rules to control where the database can be accessed from,
    # in addition to the control-plane cluster.
    firewallRules: ${TYGER_ENVIRONMENT_FIREWALL_RULES}

  # Tags to apply to all resources and resource groups
  resourceTags:

organizations:
  - name: lamna
    cloud:
      storage:
        # Storage accounts for buffers.
        buffers:
          - name: ${TYGER_ENVIRONMENT_NAME_NO_DASHES}lamnabuf
            # location: defaults to defaultLocation
            # sku: defaults to Standard_LRS
            # dnsEndpointType can be set to `AzureDNSZone` when creating large number of accounts in a single subscription.
            dnsEndpointType: AzureDnsZone
          - name: ${TYGER_ENVIRONMENT_NAME_NO_DASHES}lamnabuf2
            # location: defaults to defaultLocation
            # sku: defaults to Standard_LRS
            # dnsEndpointType can be set to `AzureDNSZone` when creating large number of accounts in a single subscription.
            dnsEndpointType: AzureDnsZone
          - name: ${TYGER_ENVIRONMENT_NAME_NO_DASHES}lamnabuf3
            location: ${TYGER_SECONDARY_LOCATION}
            # sku: defaults to Standard_LRS
            # dnsEndpointType can be set to `AzureDNSZone` when creating large number of accounts in a single subscription.
            dnsEndpointType: AzureDnsZone

        defaultBufferLocation: ${TYGER_LOCATION}

        # The storage account where run logs will be stored.
        logs:
          name: ${TYGER_ENVIRONMENT_NAME_NO_DASHES}lamnalog
          # location: defaults to defaultLocation
          # sku: defaults to Standard_LRS
          # dnsEndpointType can be set to `AzureDNSZone` when creating large number of accounts in a single subscription.
          # dnsEndpointType: defaults to Standard.

      # An optional array of managed identities that will be created in the resource group.
      # These identities are available to runs as workload identities. When updating this list
      # both `tyger cloud install` and `tyger api installed` must be run.
      identities:
        - test-identity

    api:
      # The fully qualified domain name for the Tyger API.
      domainName: lamna-${TYGER_ENVIRONMENT_NAME}.eminence.ms

      # Set to KeyVault if using a custom TLS certificate, otherwise set to LetsEncrypt
      tlsCertificateProvider: KeyVault

      accessControl:
        tenantId: 72f988bf-86f1-41af-91ab-2d7cd011db47
        apiAppUri: api://tyger-server
        cliAppUri: api://tyger-cli

        apiAppId: fc9d1bea-71ff-4cdb-8a07-69fa7df25f95
        cliAppId: 9985c0a8-7477-4ec8-a784-e24c90d98887

        serviceManagementReference: 7933f882-e109-49d5-a771-e1be70099806

        # Principals in role assignments are specified in the following ways:
        #
        # For users, specify the object ID and/or the user principal name.
        #   - kind: User
        #     objectId: <objectId>
        #     userPrincipalName: <userPrincipalName>
        #
        # For groups, specify the object ID and/or the group display name.
        #   - kind: Group
        #     objectId: <objectId>
        #     displayName: <displayName>
        #
        # For service principals, specify the object ID and/or the service principal display name.
        #   - kind: ServicePrincipal
        #     objectId: <objectId>
        #     displayName: <displayName>

        roleAssignments:
          owner:
            - kind: Group
              objectId: 36043a62-1383-4012-95aa-44da0a4d8012
              displayName: Biomedical Signal Processing Team ALT

            - kind: ServicePrincipal
              objectId: fef7e0d4-da9b-42ac-8707-5e206e04ea3a
              displayName: tyger-client-owner

          contributor:
            - kind: ServicePrincipal
              objectId: 15bf92f7-9210-480f-a6ad-8d576d0baac7
              displayName: tyger-client-contributor

        miseImage: eminence.azurecr.io/mise-sidecar:dev-1-37-0

      buffers:
        # TTL for active buffers before they are automatically soft-deleted (D.HH:MM:SS) (0 = never expire)
        activeLifetime: 0.00:00
        # TTL for soft-deleted buffers before they are automatically purged forever (D.HH:MM:SS) (0 = purge immediately)
        softDeletedLifetime: 1.00:00

      # Optional Helm chart overrides
      helm:
        tyger:
          # repoName:
          # repoUrl: not set if using `chartRef`
          chartRef: ${TYGER_HELM_CHART_DIR}
          # version:
          values:
            bufferCopierImage: ${BUFFER_COPIER_IMAGE}
            bufferSidecarImage: ${BUFFER_SIDECAR_IMAGE}
            image: ${TYGER_SERVER_IMAGE}
            workerWaiterImage: ${WORKER_WAITER_IMAGE}
