environmentName: ${TYGER_ENVIRONMENT_NAME}
cloud:
  tenantId: 72f988bf-86f1-41af-91ab-2d7cd011db47
  subscriptionId: 87d8acb3-5176-4651-b457-6ab9cefd8e3d
  defaultLocation: ${TYGER_LOCATION}
  resourceGroup: ${TYGER_ENVIRONMENT_NAME}
  logAnalyticsWorkspace:
    resourceGroup: eminence
    name: eminence
  compute:
    clusters:
      - name: ${TYGER_ENVIRONMENT_NAME}
        apiHost: true
        kubernetesVersion: 1.27
        localDevelopmentIdentityId: c0e60aba-35f0-4778-bc9b-fc5d2af14687
        userNodePools:
          - name: cpunp
            vmSize: Standard_DS12_v2
            minCount: ${TYGER_MIN_NODE_COUNT}
            maxCount: 10
          - name: gpunp
            vmSize: Standard_NC6s_v3
            minCount: ${TYGER_MIN_NODE_COUNT}
            maxCount: 10

    managementPrincipals:
      - id: 2e092785-472a-4ea1-9700-4d15646d9e91
        kind: ServicePrincipal
      - id: c0e60aba-35f0-4778-bc9b-fc5d2af14687
        kind: Group

    privateContainerRegistries:
      - eminence

  storage:
    buffers:
      - name: ${TYGER_ENVIRONMENT_NAME_NO_DASHES}tygerbuf
    logs:
      name: ${TYGER_ENVIRONMENT_NAME_NO_DASHES}tygerlog

  database:
    location: westus3
    firewallRules: ${TYGER_ENVIRONMENT_FIREWALL_RULES}

api:
  domainName: ${TYGER_ENVIRONMENT_NAME}-tyger.westus2.cloudapp.azure.com
  auth:
    tenantId: 76d3279b-830e-4bea-baf8-12863cdeba4c
    apiAppUri: api://tyger-server
    cliAppUri: api://tyger-cli
  helm:
    tyger:
      chartRef: ${TYGER_HELM_CHART_DIR}
      values:
        image: ${TYGER_SERVER_IMAGE}
        bufferSidecarImage: ${BUFFER_SIDECAR_IMAGE}
        workerWaiterImage: ${WORKER_WAITER_IMAGE}
