kind: docker

dataPlanePrimarySigningCertificate: ${HOME}/tyger_local_data_plane_cert_latest.pem

controlPlaneImage: ${TYGER_SERVER_IMAGE}
dataPlaneImage: ${TYGER_DATA_PLANE_SERVER_IMAGE}
bufferSidecarImage: ${BUFFER_SIDECAR_IMAGE}
