kind: docker

signingKeys:
  primary:
    public: ${HOME}/tyger_local_signing_key_public.pem
    private: ${HOME}/tyger_local_signing_key_private.pem

controlPlaneImage: ${TYGER_SERVER_IMAGE}
dataPlaneImage: ${TYGER_DATA_PLANE_SERVER_IMAGE}
bufferSidecarImage: ${BUFFER_SIDECAR_IMAGE}
