kind: docker


installationPath: ${TYGER_INSTALLATION_PATH}
dataPlanePort: 46339

signingKeys:
  primary:
    public: ${HOME}/tyger_local_signing_key_public.pem
    private: ${HOME}/tyger_local_signing_key_private.pem

useGateway: true

controlPlaneImage: ${TYGER_SERVER_IMAGE}
dataPlaneImage: ${TYGER_DATA_PLANE_SERVER_IMAGE}
bufferSidecarImage: ${BUFFER_SIDECAR_IMAGE}
gatewayImage: ${GATEWAY_IMAGE}

network:
  subnet: 172.20.0.0/16

buffers:
  activeLifetime: 0.00:00
  softDeletedLifetime: 0.12:00:00
