apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: whoami-cert # CHANGE THIS NAME
  namespace: default
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: jostairs@microsoft.com
    privateKeySecretRef:
      name: whoami-cert # CHANGE THIS NAME TO MATCH THE METADATA
    solvers:
    - http01:
        ingress:
          class: traefik