environmentName: js

# Cloud infrastructure configuration
cloud:
  tenantId: 72f988bf-86f1-41af-91ab-2d7cd011db47
  subscriptionId: biomedicalimaging-nonprod
  defaultLocation: westus2

  compute:
    clusters:
      - name: js
        apiHost: true
        # location: westus2
        # kubernetesVersion: ""
        userNodePools:
          - name: cpunp
            vmSize: Standard_DS2_v2
            # minCount: 0
            maxCount: 10
          - name: gpunp
            vmSize: Standard_NC6s_v3
            # minCount: 0
            maxCount: 10
    managementPrincipalIds: []
    privateContainerRegistries:
      - eminence

  storage:
    buffers:
      - name: jstygerbuf
        # location: ""
        # sku: ""
    logs:
      name: jstygerlog
      # location: ""
      # sku: ""

# Tyger API configuration
api:
  domainName: js-tyger.westus2.cloudapp.azure.com

  auth:
    tenantId: 76d3279b-830e-4bea-baf8-12863cdeba4c
    ApiAppUri: "api://tyger-server"
    cliAppUri: "api://tyger-cli"

  # optional Helm overrides
  helm:
    tyger:
      chartRef: /workspaces/tyger/deploy/helm/tyger
      values:
        server:
          image: eminence.azurecr.io/tyger-server@sha256:4a0a2a55b28839ee8dbace1257057f63f51aea1ff87e9333b9b8ca9fef3c4a31
          bufferSidecarImage: eminence.azurecr.io/buffer-sidecar@sha256:cf7bdf802b7065a3dfed8818655c7600e139ca54ab2579f977fa894129b0ba71
          workerWaiterImage: eminence.azurecr.io/worker-waiter@sha256:0b71d9edece1fad1715f8d59d481c3db2618ea572fbbc6b18af4c2645857df38

    # certManager:
    #   chartRepo: https://charts.jetstack.io
    #   chartVersion: v1.0.2
    #   values:

    # traefik:
    #   chartRepo: https://containous.github.io/traefik-helm-chart
    #   chartVersion: 9.14.2
    #   values:

    # nvidiaDevicePlugin:
    #   chartRepo: https://containous.github.io/traefik-helm-chart
    #   chartVersion: 9.14.2
    #   values:
