before:
  hooks:
    - go mod tidy

builds:
  - id: tyger
    main: ./cmd/tyger
    binary: tyger
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X main.version={{ .Tag }}
      - -X github.com/microsoft/tyger/cli/internal/install.ContainerRegistry={{ .Env.GORELEASER_CONTAINER_REGISTRY }}
      - -X github.com/microsoft/tyger/cli/internal/install.ContainerRegistryDirectory={{ .Env.GORELEASER_CONTAINER_REGISTRY_DIRECTORY }}
      - -X github.com/microsoft/tyger/cli/internal/install.ContainerImageTag={{ .Tag }}
    goos:
      - linux
      - windows
      - darwin

  - id: tyger-proxy
    main: ./cmd/tyger-proxy
    binary: tyger-proxy
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X main.version={{.Tag}}
    goos:
      - linux
      - windows
      - darwin

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  draft: true
  replace_existing_draft: true
