# Use postgres/example user/password credentials
version: "3.1"

services:
  db:
    image: postgres
    restart: always
    command:
      - -c
      - listen_addresses=localhost
    volumes:
      - db_data:/var/lib/postgresql/data
      - type: bind
        source: /opt/tyger/pg
        target: /var/run/postgresql/

    network_mode: none

    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: tyger-server

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tyger-server"]
      interval: 2s
      timeout: 60s
      retries: 5
      start_period: 80s

  data-plane:
    build:
      context: ..
      dockerfile: server/Dockerfile
      target: data-plane

    environment:
      Urls: http://unix:/opt/tyger/tyger.data.sock
      Auth__Enabled: "false"
      DataDirectory: /opt/tyger/buffers
      LogArchive__LocalStorage__LogsDirectory: /opt/tyger/logs
      primarySigningCertificatePath: /opt/tyger/secrets/tyger_local_buffer_service_cert_latest_public.pem

    volumes:
      - type: bind
        source: /opt/tyger
        target: /opt/tyger

    user: "502632372" # TODO: hack!

  control-plane:
    build:
      context: ..
      dockerfile: server/Dockerfile
      target: control-plane

    environment:
      Urls: http://unix:/opt/tyger/tyger.sock
      Auth__Enabled: "false"
      Compute__Docker__RunSecretsPath: /opt/tyger/secrets/runs
      LogArchive__LocalStorage__LogsDirectory: /opt/tyger/logs
      Buffers__LocalStorage__SigningCertificatePath: /opt/tyger/secrets/tyger_local_buffer_service_cert_latest.pem
      Buffers__LocalStorage__DataPlaneEndpoint: http+unix:///opt/tyger/tyger.data.sock
      Buffers__BufferSidecarImage: eminence.azurecr.io/buffer-sidecar:dev
      Database__ConnectionString: Host=/opt/tyger/pg; Username=tyger-server
      Database__AutoMigrate: "true"
      Database__TygerServerRoleName: tyger-server

    volumes:
      - type: bind
        source: /opt/tyger
        target: /opt/tyger

      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock

    user: "502632372:9005" # TODO: hack!

    network_mode: none

volumes:
  db_data:
