# Use postgres/example user/password credentials
version: "3.1"

services:
  db:
    image: postgres
    restart: always
    command:
      - -c
      - listen_addresses=localhost
    volumes:
      - db_data:/var/lib/postgresql/data
      - type: bind
        source: /opt/tyger/pg
        target: /var/run/postgresql/

    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: tyger-server

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tyger-server"]
      interval: 2s
      timeout: 60s
      retries: 5
      start_period: 80s

volumes:
  db_data:
