name: "Tyger Dependency Check"

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:
  pull_request:
    branches: [main]

permissions:
  id-token: write
  contents: write
  pull-requests: write

jobs:
  dependency-check:
    runs-on: ubuntu-latest
    container:
      image: compimagdevcontainers.azurecr.io/tyger@sha256:df2df5320e642fda8e70e40570f899064a9758822481e3ab8aa2715527d8dd78
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2

      - name: "Login into Azure"
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: "Dependency Check"
        env:
            GH_TOKEN: ${{ github.token }}
        run: |
            set -eo pipefail
            source /opt/conda/etc/profile.d/conda.sh
            conda activate /opt/conda/envs/tyger
            ./scripts/check-for-dependency-updates.sh --simulate --pr
